name: Pull Requests

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
      - "releases/v*"
  pull_request:
    branches:
      - "releases/v*"
      - development

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  formatCheck:
    name: Checks Source Code Formatting
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup CommandBox CLI
        uses: Ortus-Solutions/setup-commandbox@v2.0.1
        with:
          install: commandbox-cfformat
          warmup: true

      - name: Run formatting rules
        run: box run-script format:check
